version: 2

builds:
  - env:
      - CGO_ENABLED=0
    flags:
      - -trimpath
    ldflags:
      - -s -w
    goos:
      - linux
      - windows
      - darwin

upx:
  - enabled: true
    goos: [linux, darwin]
    compress: best
    lzma: true
    brute: true

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

dockers:
  -
    image_templates:
      - ghcr.io/lovelaze/nebula-sync:latest
      - ghcr.io/lovelaze/nebula-sync:{{ .Tag }}
    goos: linux

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
